import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-center'>


        
        <p className='font-bold text-xl m-5'>Welcome</p>
        <Link className='mr-3 text-blue-500' href="/login"> Log In</Link>
        <Link className='text-blue-500' href="/register"> Register</Link>
        <Link href="/"></Link>
      </main>
    </>
  )
}
